// src/features/walletConnect/components/IOSWalletModal.vue
<template>
  <div class="ios-modal-overlay" :class="{ 'dark-mode': isDarkMode }" @click="handleOverlayClick">
    <div class="ios-modal" :class="{ 'dark-mode': isDarkMode }" @click.stop>
      <!-- Content -->
      <div class="ios-modal-content">
        <!-- QR Code Section -->
        <div class="qr-section">
          <div class="qr-container">
            <div id="ios-qr-code" class="qr-code" ref="qrCodeRef">
              <!-- QR code will be inserted here -->
            </div>
            <div v-if="qrCodeLoading" class="qr-loading-overlay">
              <div class="spinner"></div>
              <p>Generating QR code...</p>
            </div>
            <div v-if="qrCodeError" class="qr-error-overlay">
              <svg
                width="48"
                height="48"
                viewBox="0 0 24 24"
                fill="currentColor"
                class="error-icon"
              >
                <path
                  d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"
                />
              </svg>
              <p>Failed to generate QR code</p>
              <button @click="generateQRCode" class="retry-button">Retry</button>
            </div>
          </div>
        </div>

        <!-- URI Section -->
        <div class="uri-section">
          <div class="uri-header">
            <h4>Connection String</h4>
            <div
              class="copy-status"
              :class="{ copied: copyStatus === 'copied', error: copyStatus === 'error' }"
            >
              <span v-if="copyStatus === 'copied'">✓ Copied!</span>
              <span v-else-if="copyStatus === 'error'">✗ Failed</span>
            </div>
          </div>

          <div class="uri-input-container">
            <textarea
              ref="uriTextarea"
              :value="props.uri"
              readonly
              class="uri-textarea"
              placeholder="Connection string will appear here..."
              @focus="selectAll"
            ></textarea>
            <button
              @click="copyToClipboard"
              class="copy-button"
              :disabled="!props.uri || copyStatus === 'copied'"
            >
              <svg
                v-if="copyStatus !== 'copied'"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="currentColor"
              >
                <path
                  d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"
                />
              </svg>
              <svg v-else width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
              </svg>
              {{ copyStatus === 'copied' ? 'Copied!' : 'Copy' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="ios-modal-footer">
        <div class="footer-buttons">
          <button @click="closeModal" class="cancel-button">Cancel</button>
          <button @click="handleContinue" class="continue-button" :disabled="!isWalletConnected">
            Continue
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { computed, onMounted, ref } from 'vue'

  interface Props {
    uri: string
  }

  interface Emits {
    (e: 'close'): void
    (e: 'continue'): void
  }

  const props = defineProps<Props>()
  const emit = defineEmits<Emits>()

  const qrCodeRef = ref<HTMLElement>()
  const uriTextarea = ref<HTMLTextAreaElement>()

  const qrCodeLoading = ref(false)
  const qrCodeError = ref(false)
  const copyStatus = ref<'idle' | 'copied' | 'error'>('idle')
  const isWalletConnected = ref(false)

  const isDarkMode = computed(() => {
    if (typeof window === 'undefined') return false
    return window.matchMedia('(prefers-color-scheme: dark)').matches
  })

  onMounted(() => {
    generateQRCode()
  })

  const ensureQRCodeRef = (): boolean => {
    if (!qrCodeRef.value) {
      const fallbackElement = document.getElementById('ios-qr-code')
      if (fallbackElement) {
        // Using fallback element for QR code
        qrCodeRef.value = fallbackElement as HTMLElement
        return true
      }
      // QR code ref not available and no fallback found
      return false
    }
    return true
  }

  const generateQRCode = async (): Promise<void> => {
    if (!props.uri) {
      // No URI provided for QR code generation
      return
    }

    // Validate URI format
    if (!props.uri.startsWith('wc:')) {
      // Invalid WalletConnect URI format
      qrCodeError.value = true
      qrCodeLoading.value = false
      return
    }

    if (!ensureQRCodeRef()) {
      setTimeout(() => generateQRCode(), 100)
      return
    }

    qrCodeLoading.value = true
    qrCodeError.value = false

    try {
      const QRCodeModule = await import('qrcode')
      const QRCode = QRCodeModule.default
      const qrCodeDataUrl = await QRCode.toDataURL(props.uri, {
        width: 180,
        margin: 2,
        color: {
          dark: isDarkMode.value ? '#FFFFFF' : '#000000',
          light: isDarkMode.value ? '#1C1C1E' : '#FFFFFF',
        },
        errorCorrectionLevel: 'M',
      })

      const qrCodeImg = document.createElement('img')
      qrCodeImg.src = qrCodeDataUrl
      qrCodeImg.alt = 'WalletConnect QR Code'
      qrCodeImg.className = 'qr-image'
      qrCodeImg.style.width = '180px'
      qrCodeImg.style.height = '180px'
      qrCodeImg.style.borderRadius = '16px'
      qrCodeImg.style.border = isDarkMode.value
        ? '1px solid rgba(255, 255, 255, 0.1)'
        : '1px solid rgba(0, 0, 0, 0.1)'
      qrCodeImg.style.boxShadow = isDarkMode.value
        ? '0 8px 24px rgba(0, 0, 0, 0.3)'
        : '0 8px 24px rgba(0, 0, 0, 0.1)'

      qrCodeImg.onerror = () => {
        // QR code image failed to load
        qrCodeError.value = true
        qrCodeLoading.value = false
      }

      qrCodeImg.onload = () => {
        // QR code image loaded successfully
      }

      if (!ensureQRCodeRef()) {
        // QR code ref became null during generation
        qrCodeError.value = true
        qrCodeLoading.value = false
        return
      }

      const qrElement = qrCodeRef.value!
      qrElement.innerHTML = ''
      qrElement.appendChild(qrCodeImg)

      qrCodeLoading.value = false
    } catch {
      // Failed to generate QR code
      // Error details
      qrCodeLoading.value = false
      qrCodeError.value = true
    }
  }

  const copyToClipboard = async (): Promise<void> => {
    if (!props.uri) return

    copyStatus.value = 'idle'

    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(props.uri)
        copyStatus.value = 'copied'
        // Text copied to clipboard (modern API)
        return
      }

      const textarea = document.createElement('textarea')
      textarea.value = props.uri
      textarea.style.position = 'fixed'
      textarea.style.left = '-999999px'
      textarea.style.top = '-999999px'
      document.body.appendChild(textarea)

      textarea.focus()
      textarea.select()

      const successful = document.execCommand('copy')
      document.body.removeChild(textarea)

      if (successful) {
        copyStatus.value = 'copied'
        // Text copied to clipboard (fallback method)
      } else {
        throw new Error('execCommand failed')
      }
    } catch {
      // Copy failed
      copyStatus.value = 'error'
    }

    setTimeout(() => {
      copyStatus.value = 'idle'
    }, 3000)
  }

  const selectAll = (): void => {
    if (uriTextarea.value) {
      uriTextarea.value.select()
    }
  }

  const handleContinue = (): void => {
    emit('continue')
  }

  const closeModal = (): void => {
    emit('close')
  }

  const handleOverlayClick = (event: MouseEvent): void => {
    if (event.target === event.currentTarget) {
      closeModal()
    }
  }
</script>

<style scoped>
  .ios-modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.3);
    backdrop-filter: blur(20px) saturate(180%);
    -webkit-backdrop-filter: blur(20px) saturate(180%);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    padding: 16px;
    animation: fadeIn 0.3s ease-out;
  }

  .ios-modal-overlay.dark-mode {
    background: rgba(0, 0, 0, 0.6);
  }

  .ios-modal {
    background: rgba(255, 255, 255, 0.95);
    backdrop-filter: blur(20px) saturate(180%);
    -webkit-backdrop-filter: blur(20px) saturate(180%);
    border-radius: 20px;
    border: 1px solid rgba(255, 255, 255, 0.2);
    box-shadow:
      0 20px 40px -12px rgba(0, 0, 0, 0.15),
      0 0 0 1px rgba(255, 255, 255, 0.1),
      inset 0 1px 0 rgba(255, 255, 255, 0.1);
    max-width: 340px;
    width: 100%;
    max-height: 85vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    animation: slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1);
  }

  .ios-modal.dark-mode {
    background: rgba(28, 28, 30, 0.95);
    border: 1px solid rgba(255, 255, 255, 0.1);
    box-shadow:
      0 20px 40px -12px rgba(0, 0, 0, 0.4),
      0 0 0 1px rgba(255, 255, 255, 0.05),
      inset 0 1px 0 rgba(255, 255, 255, 0.05);
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  @keyframes slideUp {
    from {
      opacity: 0;
      transform: translateY(20px) scale(0.95);
    }
    to {
      opacity: 1;
      transform: translateY(0) scale(1);
    }
  }

  .ios-modal-header {
    padding: 20px 20px 16px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.05);
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    background: linear-gradient(135deg, rgba(255, 255, 255, 0.8) 0%, rgba(255, 255, 255, 0.4) 100%);
  }

  .ios-modal.dark-mode .ios-modal-header {
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    background: linear-gradient(135deg, rgba(28, 28, 30, 0.8) 0%, rgba(28, 28, 30, 0.4) 100%);
  }

  .header-content {
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .app-icon {
    width: 44px;
    height: 44px;
    border-radius: 12px;
    overflow: hidden;
    background: linear-gradient(135deg, #007aff 0%, #5856d6 100%);
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow:
      0 6px 12px rgba(0, 122, 255, 0.3),
      inset 0 1px 0 rgba(255, 255, 255, 0.2);
  }

  .app-icon .icon {
    width: 100%;
    height: 100%;
    object-fit: cover;
    border-radius: 12px;
  }

  .header-text h3 {
    margin: 0 0 4px 0;
    font-size: 18px;
    font-weight: 700;
    color: #1d1d1f;
    letter-spacing: -0.02em;
  }

  .ios-modal.dark-mode .header-text h3 {
    color: #ffffff;
  }

  .header-text p {
    margin: 0;
    font-size: 14px;
    color: #86868b;
    font-weight: 400;
    line-height: 1.3;
  }

  .ios-modal.dark-mode .header-text p {
    color: #8e8e93;
  }

  .close-button {
    background: rgba(0, 0, 0, 0.05);
    border: none;
    padding: 8px;
    border-radius: 10px;
    color: #86868b;
    cursor: pointer;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
  }

  .ios-modal.dark-mode .close-button {
    background: rgba(255, 255, 255, 0.1);
    color: #8e8e93;
  }

  .close-button:hover {
    background: rgba(0, 0, 0, 0.1);
    color: #1d1d1f;
    transform: scale(1.05);
  }

  .ios-modal.dark-mode .close-button:hover {
    background: rgba(255, 255, 255, 0.15);
    color: #ffffff;
  }

  .close-button:active {
    transform: scale(0.95);
  }

  .ios-modal-content {
    padding: 20px;
    flex: 1;
    overflow-y: auto;
  }

  .qr-section {
    margin-bottom: 20px;
  }

  .qr-container {
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 180px;
    background: linear-gradient(135deg, rgba(255, 255, 255, 0.8) 0%, rgba(248, 250, 252, 0.6) 100%);
    border-radius: 16px;
    padding: 20px;
    border: 1px solid rgba(255, 255, 255, 0.3);
    box-shadow:
      inset 0 1px 0 rgba(255, 255, 255, 0.1),
      0 4px 12px rgba(0, 0, 0, 0.05);
  }

  .ios-modal.dark-mode .qr-container {
    background: linear-gradient(135deg, rgba(28, 28, 30, 0.8) 0%, rgba(44, 44, 46, 0.6) 100%);
    border: 1px solid rgba(255, 255, 255, 0.1);
    box-shadow:
      inset 0 1px 0 rgba(255, 255, 255, 0.05),
      0 4px 12px rgba(0, 0, 0, 0.2);
  }

  .qr-loading-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(255, 255, 255, 0.95);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
    color: #86868b;
    border-radius: 16px;
  }

  .ios-modal.dark-mode .qr-loading-overlay {
    background: rgba(28, 28, 30, 0.95);
    color: #8e8e93;
  }

  .qr-error-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(255, 255, 255, 0.95);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
    color: #86868b;
    border-radius: 16px;
  }

  .ios-modal.dark-mode .qr-error-overlay {
    background: rgba(28, 28, 30, 0.95);
    color: #8e8e93;
  }

  .spinner {
    width: 28px;
    height: 28px;
    border: 2px solid rgba(0, 0, 0, 0.1);
    border-top: 2px solid #007aff;
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  .ios-modal.dark-mode .spinner {
    border: 2px solid rgba(255, 255, 255, 0.1);
    border-top: 2px solid #007aff;
  }

  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }

  .error-icon {
    color: #ff3b30;
    opacity: 0.8;
  }

  .retry-button {
    background: linear-gradient(135deg, #007aff 0%, #5856d6 100%);
    color: white;
    border: none;
    padding: 10px 16px;
    border-radius: 10px;
    cursor: pointer;
    font-size: 14px;
    font-weight: 600;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    box-shadow: 0 4px 12px rgba(0, 122, 255, 0.3);
  }

  .retry-button:hover {
    transform: translateY(-1px);
    box-shadow: 0 6px 16px rgba(0, 122, 255, 0.4);
  }

  .retry-button:active {
    transform: translateY(0);
  }

  .qr-code {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .qr-image {
    max-width: 100%;
    height: auto;
    border-radius: 16px;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);
  }

  .uri-section {
    margin-bottom: 20px;
  }

  .uri-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 12px;
  }

  .uri-header h4 {
    margin: 0;
    font-size: 16px;
    font-weight: 700;
    color: #1d1d1f;
    letter-spacing: -0.02em;
  }

  .ios-modal.dark-mode .uri-header h4 {
    color: #ffffff;
  }

  .copy-status {
    font-size: 12px;
    font-weight: 600;
    padding: 4px 10px;
    border-radius: 8px;
    transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
  }

  .copy-status.copied {
    background: rgba(52, 199, 89, 0.15);
    color: #34c759;
    border: 1px solid rgba(52, 199, 89, 0.2);
  }

  .ios-modal.dark-mode .copy-status.copied {
    background: rgba(52, 199, 89, 0.2);
    color: #30d158;
  }

  .copy-status.error {
    background: rgba(255, 59, 48, 0.15);
    color: #ff3b30;
    border: 1px solid rgba(255, 59, 48, 0.2);
  }

  .ios-modal.dark-mode .copy-status.error {
    background: rgba(255, 59, 48, 0.2);
    color: #ff453a;
  }

  .uri-input-container {
    position: relative;
  }

  .uri-textarea {
    width: 100%;
    min-height: 70px;
    padding: 12px 60px 12px 12px; /* Add right padding to prevent text overlap with copy button */
    border: 1px solid rgba(0, 0, 0, 0.1);
    border-radius: 12px;
    font-family:
      'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
    font-size: 12px;
    line-height: 1.4;
    color: #1d1d1f;
    background: rgba(255, 255, 255, 0.8);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    resize: vertical;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);
  }

  .ios-modal.dark-mode .uri-textarea {
    border: 1px solid rgba(255, 255, 255, 0.1);
    color: #ffffff;
    background: rgba(28, 28, 30, 0.8);
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);
  }

  .uri-textarea:focus {
    outline: none;
    border-color: #007aff;
    background: rgba(255, 255, 255, 0.95);
    box-shadow:
      inset 0 1px 0 rgba(255, 255, 255, 0.1),
      0 0 0 3px rgba(0, 122, 255, 0.1);
  }

  .ios-modal.dark-mode .uri-textarea:focus {
    background: rgba(28, 28, 30, 0.95);
    box-shadow:
      inset 0 1px 0 rgba(255, 255, 255, 0.05),
      0 0 0 3px rgba(0, 122, 255, 0.2);
  }

  .copy-button {
    position: absolute;
    top: 8px;
    right: 8px;
    background: linear-gradient(135deg, #007aff 0%, #5856d6 100%);
    color: white;
    border: none;
    padding: 10px 14px;
    border-radius: 12px;
    cursor: pointer;
    font-size: 13px;
    font-weight: 600;
    display: flex;
    align-items: center;
    gap: 6px;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    box-shadow: 0 4px 16px rgba(0, 122, 255, 0.4);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    z-index: 10;
    min-width: 80px;
    justify-content: center;
  }

  .copy-button:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 8px 20px rgba(0, 122, 255, 0.5);
    background: linear-gradient(135deg, #0056cc 0%, #4c3db8 100%);
  }

  .copy-button:active:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(0, 122, 255, 0.3);
  }

  .copy-button:disabled {
    background: rgba(0, 0, 0, 0.1);
    color: rgba(0, 0, 0, 0.4);
    cursor: not-allowed;
    transform: none;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    opacity: 0.6;
  }

  .ios-modal.dark-mode .copy-button:disabled {
    background: rgba(255, 255, 255, 0.1);
    color: rgba(255, 255, 255, 0.4);
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
  }

  .instructions-section h4 {
    margin: 0 0 16px 0;
    font-size: 16px;
    font-weight: 700;
    color: #1d1d1f;
    letter-spacing: -0.02em;
  }

  .ios-modal.dark-mode .instructions-section h4 {
    color: #ffffff;
  }

  .steps {
    display: flex;
    flex-direction: column;
    gap: 14px;
  }

  .step {
    display: flex;
    align-items: flex-start;
    gap: 12px;
  }

  .step-number {
    width: 24px;
    height: 24px;
    background: linear-gradient(135deg, #007aff 0%, #5856d6 100%);
    color: white;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 12px;
    font-weight: 700;
    flex-shrink: 0;
    box-shadow: 0 4px 12px rgba(0, 122, 255, 0.3);
  }

  .step-content p {
    margin: 0;
    font-size: 14px;
    color: #1d1d1f;
    line-height: 1.4;
    font-weight: 400;
  }

  .ios-modal.dark-mode .step-content p {
    color: #ffffff;
  }

  .ios-modal-footer {
    padding: 16px 20px 20px;
    border-top: 1px solid rgba(0, 0, 0, 0.05);
    background: linear-gradient(135deg, rgba(255, 255, 255, 0.8) 0%, rgba(255, 255, 255, 0.4) 100%);
  }

  .ios-modal.dark-mode .ios-modal-footer {
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    background: linear-gradient(135deg, rgba(28, 28, 30, 0.8) 0%, rgba(28, 28, 30, 0.4) 100%);
  }

  .footer-buttons {
    display: flex;
    gap: 12px;
  }

  .cancel-button {
    flex: 1;
    background: rgba(0, 0, 0, 0.05);
    color: #1d1d1f;
    border: none;
    padding: 14px;
    border-radius: 12px;
    cursor: pointer;
    font-size: 16px;
    font-weight: 600;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
  }

  .ios-modal.dark-mode .cancel-button {
    background: rgba(255, 255, 255, 0.1);
    color: #ffffff;
  }

  .cancel-button:hover {
    background: rgba(0, 0, 0, 0.1);
    transform: translateY(-1px);
  }

  .ios-modal.dark-mode .cancel-button:hover {
    background: rgba(255, 255, 255, 0.15);
  }

  .cancel-button:active {
    transform: translateY(0);
  }

  .continue-button {
    flex: 1;
    background: linear-gradient(135deg, #007aff 0%, #5856d6 100%);
    color: white;
    border: none;
    padding: 14px;
    border-radius: 12px;
    cursor: pointer;
    font-size: 16px;
    font-weight: 600;
    transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    box-shadow: 0 4px 12px rgba(0, 122, 255, 0.3);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
  }

  .continue-button:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 6px 16px rgba(0, 122, 255, 0.4);
  }

  .continue-button:active:not(:disabled) {
    transform: translateY(0);
  }

  .continue-button:disabled {
    background: rgba(0, 0, 0, 0.1);
    color: rgba(0, 0, 0, 0.3);
    cursor: not-allowed;
    transform: none;
    box-shadow: none;
  }

  .ios-modal.dark-mode .continue-button:disabled {
    background: rgba(255, 255, 255, 0.1);
    color: rgba(255, 255, 255, 0.3);
  }

  /* Mobile optimizations */
  @media (max-width: 480px) {
    .ios-modal-overlay {
      padding: 12px;
    }

    .ios-modal {
      border-radius: 16px;
      max-height: 90vh;
      max-width: 320px;
    }

    .ios-modal-header {
      padding: 16px 16px 12px;
    }

    .ios-modal-content {
      padding: 16px;
    }

    .ios-modal-footer {
      padding: 12px 16px 16px;
    }

    .app-icon {
      width: 40px;
      height: 40px;
      border-radius: 10px;
    }

    .header-text h3 {
      font-size: 16px;
    }

    .header-text p {
      font-size: 13px;
    }

    .qr-container {
      min-height: 160px;
      padding: 16px;
    }

    .uri-textarea {
      font-size: 11px;
      min-height: 60px;
      padding: 10px;
    }

    .copy-button {
      padding: 6px 10px;
      font-size: 11px;
    }

    .instructions-section h4 {
      font-size: 15px;
    }

    .step-content p {
      font-size: 13px;
    }

    .step-number {
      width: 20px;
      height: 20px;
      font-size: 11px;
    }

    .cancel-button {
      padding: 12px;
      font-size: 15px;
    }
  }

  /* iOS-specific optimizations */
  @supports (-webkit-touch-callout: none) {
    .ios-modal-overlay {
      -webkit-overflow-scrolling: touch;
    }

    .uri-textarea {
      -webkit-appearance: none;
      -webkit-tap-highlight-color: transparent;
    }

    .copy-button,
    .cancel-button,
    .retry-button {
      -webkit-tap-highlight-color: transparent;
    }
  }
</style>

// pengui/src/features/walletConnect/components/IOSWalletModal.tsx
'use client'

import { useEffect, useRef, useState } from 'react'

interface IOSWalletModalProps {
  uri: string
  isOpen: boolean
  onClose: () => void
  onContinue?: () => void
}

export function IOSWalletModal({ uri, isOpen, onClose, onContinue }: IOSWalletModalProps) {
  const qrCodeRef = useRef<HTMLDivElement>(null)
  const uriTextareaRef = useRef<HTMLTextAreaElement>(null)
  const [qrCodeLoading, setQrCodeLoading] = useState(false)
  const [qrCodeError, setQrCodeError] = useState(false)
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'error'>('idle')
  const [isDarkMode, setIsDarkMode] = useState(false)

  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
    setIsDarkMode(mediaQuery.matches)

    const handleChange = (e: MediaQueryListEvent) => setIsDarkMode(e.matches)
    mediaQuery.addEventListener('change', handleChange)
    return () => mediaQuery.removeEventListener('change', handleChange)
  }, [])

  useEffect(() => {
    if (isOpen && uri) {
      generateQRCode()
    }
  }, [isOpen, uri])

  const generateQRCode = async () => {
    if (!uri || !qrCodeRef.current) return

    if (!uri.startsWith('wc:')) {
      setQrCodeError(true)
      setQrCodeLoading(false)
      return
    }

    setQrCodeLoading(true)
    setQrCodeError(false)

    try {
      const QRCodeModule = await import('qrcode')
      const QRCode = QRCodeModule.default
      const qrCodeDataUrl = await QRCode.toDataURL(uri, {
        width: 180,
        margin: 2,
        color: {
          dark: isDarkMode ? '#FFFFFF' : '#000000',
          light: isDarkMode ? '#1C1C1E' : '#FFFFFF',
        },
        errorCorrectionLevel: 'M',
      })

      const qrCodeImg = document.createElement('img')
      qrCodeImg.src = qrCodeDataUrl
      qrCodeImg.alt = 'WalletConnect QR Code'
      qrCodeImg.className = 'qr-image'
      qrCodeImg.style.width = '180px'
      qrCodeImg.style.height = '180px'
      qrCodeImg.style.borderRadius = '16px'
      qrCodeImg.style.border = isDarkMode
        ? '1px solid rgba(255, 255, 255, 0.1)'
        : '1px solid rgba(0, 0, 0, 0.1)'
      qrCodeImg.style.boxShadow = isDarkMode
        ? '0 8px 24px rgba(0, 0, 0, 0.3)'
        : '0 8px 24px rgba(0, 0, 0, 0.1)'

      if (qrCodeRef.current) {
        qrCodeRef.current.innerHTML = ''
        qrCodeRef.current.appendChild(qrCodeImg)
      }

      setQrCodeLoading(false)
    } catch {
      setQrCodeLoading(false)
      setQrCodeError(true)
    }
  }

  const copyToClipboard = async () => {
    if (!uri) return

    setCopyStatus('idle')

    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(uri)
        setCopyStatus('copied')
        return
      }

      const textarea = document.createElement('textarea')
      textarea.value = uri
      textarea.style.position = 'fixed'
      textarea.style.left = '-999999px'
      textarea.style.top = '-999999px'
      document.body.appendChild(textarea)

      textarea.focus()
      textarea.select()

      const successful = document.execCommand('copy')
      document.body.removeChild(textarea)

      if (successful) {
        setCopyStatus('copied')
      } else {
        throw new Error('execCommand failed')
      }
    } catch {
      setCopyStatus('error')
    }

    setTimeout(() => {
      setCopyStatus('idle')
    }, 3000)
  }

  const selectAll = () => {
    if (uriTextareaRef.current) {
      uriTextareaRef.current.select()
    }
  }

  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose()
    }
  }

  if (!isOpen) return null

  return (
    <div
      className={`ios-modal-overlay ${isDarkMode ? 'dark-mode' : ''}`}
      onClick={handleOverlayClick}
    >
      <div
        className={`ios-modal ${isDarkMode ? 'dark-mode' : ''}`}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="ios-modal-content">
          {/* QR Code Section */}
          <div className="qr-section">
            <div className="qr-container">
              <div id="ios-qr-code" className="qr-code" ref={qrCodeRef}></div>
              {qrCodeLoading && (
                <div className="qr-loading-overlay">
                  <div className="spinner"></div>
                  <p>Generating QR code...</p>
                </div>
              )}
              {qrCodeError && (
                <div className="qr-error-overlay">
                  <svg
                    width="48"
                    height="48"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="error-icon"
                  >
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z" />
                  </svg>
                  <p>Failed to generate QR code</p>
                  <button onClick={generateQRCode} className="retry-button">
                    Retry
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* URI Section */}
          <div className="uri-section">
            <div className="uri-header">
              <h4>Connection String</h4>
              <div
                className={`copy-status ${copyStatus === 'copied' ? 'copied' : ''} ${copyStatus === 'error' ? 'error' : ''}`}
              >
                {copyStatus === 'copied' && <span>✓ Copied!</span>}
                {copyStatus === 'error' && <span>✗ Failed</span>}
              </div>
            </div>

            <div className="uri-input-container">
              <textarea
                ref={uriTextareaRef}
                value={uri}
                readOnly
                className="uri-textarea"
                placeholder="Connection string will appear here..."
                onFocus={selectAll}
              />
              <button
                onClick={copyToClipboard}
                className="copy-button"
                disabled={!uri || copyStatus === 'copied'}
              >
                {copyStatus !== 'copied' ? (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z" />
                  </svg>
                ) : (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
                  </svg>
                )}
                {copyStatus === 'copied' ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="ios-modal-footer">
          <div className="footer-buttons">
            <button onClick={onClose} className="cancel-button">
              Cancel
            </button>
            {onContinue && (
              <button onClick={onContinue} className="continue-button">
                Continue
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
