// src/components/Offers/TakeOfferModal.vue
<template>
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-lg w-full">
      <div class="p-6">
        <!-- Header -->
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-xl font-semibold text-gray-900 dark:text-white">Take Offer</h2>
          <button
            @click="$emit('close')"
            class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
          >
            <i class="pi pi-times text-xl"></i>
          </button>
        </div>

        <!-- Form -->
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Offer String Input -->
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Offer String
            </label>
            <textarea
              v-model="form.offerString"
              rows="4"
              placeholder="Paste the offer string here..."
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 resize-none"
              required
            ></textarea>
            <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
              Paste the complete offer string from the offer creator
            </p>
            <p v-if="parseError" class="mt-1 text-xs text-red-500 dark:text-red-400">
              {{ parseError }}
            </p>
            <div v-if="offerInspection.isInspecting.value" class="mt-2 flex items-center">
              <i class="pi pi-spinner pi-spin text-blue-600 dark:text-blue-400 mr-2 text-xs"></i>
              <p class="text-xs text-blue-600 dark:text-blue-400">
                Processing offer with Dexie marketplace...
              </p>
            </div>
          </div>

          <!-- Transaction Fee -->
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Transaction Fee
            </label>
            <input
              v-model.number="form.fee"
              type="number"
              step="0.000001"
              min="0"
              placeholder="0.000001"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
            <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
              Fee can be 0 for free transactions
            </p>
          </div>

          <!-- Offer Preview (if valid) -->
          <div v-if="offerPreview" class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
            <h4 class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Offer Preview</h4>
            <div class="space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-gray-600 dark:text-gray-400">You will receive:</span>
                <span class="text-gray-900 dark:text-white">
                  {{
                    offerPreview.assetsOffered?.length
                      ? offerPreview.assetsOffered
                          .map(
                            a =>
                              `${formatAssetAmount(a.amount, a.type)} ${a.symbol || a.type.toUpperCase()}`
                          )
                          .join(', ')
                      : 'Assets from offer'
                  }}
                </span>
              </div>
              <div class="flex justify-between">
                <span class="text-gray-600 dark:text-gray-400">You will pay:</span>
                <span class="text-gray-900 dark:text-white">
                  {{
                    offerPreview.assetsRequested?.length
                      ? offerPreview.assetsRequested
                          .map(
                            a =>
                              `${formatAssetAmount(a.amount, a.type)} ${a.symbol || a.type.toUpperCase()}`
                          )
                          .join(', ')
                      : 'Assets to offer creator'
                  }}
                </span>
              </div>
              <div class="flex justify-between border-t border-gray-200 dark:border-gray-600 pt-2">
                <span class="font-medium text-gray-700 dark:text-gray-300">Fee:</span>
                <span class="font-medium text-gray-900 dark:text-white">
                  {{ offerPreview.fee !== undefined ? offerPreview.fee : form.fee }} XCH
                </span>
              </div>
              <div
                v-if="offerPreview.dexieStatus !== undefined"
                class="flex justify-between border-t border-gray-200 dark:border-gray-600 pt-2"
              >
                <span class="font-medium text-gray-700 dark:text-gray-300">Status:</span>
                <span class="font-medium text-gray-900 dark:text-white">
                  {{ getDexieStatusDescription(offerPreview.dexieStatus) }}
                </span>
              </div>
              <div
                v-if="offerPreview.creatorAddress"
                class="flex justify-between border-t border-gray-200 dark:border-gray-600 pt-2"
              >
                <span class="font-medium text-gray-700 dark:text-gray-300">Creator:</span>
                <span class="font-medium text-gray-900 dark:text-white text-xs">
                  {{ offerPreview.creatorAddress.slice(0, 8) }}...{{
                    offerPreview.creatorAddress.slice(-8)
                  }}
                </span>
              </div>
            </div>
          </div>

          <!-- Error/Success Messages -->
          <div
            v-if="errorMessage"
            class="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"
          >
            <div class="flex items-center">
              <i class="pi pi-exclamation-triangle text-red-600 dark:text-red-400 mr-2"></i>
              <p class="text-red-800 dark:text-red-200">{{ errorMessage }}</p>
            </div>
          </div>

          <div
            v-if="successMessage"
            class="p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg"
          >
            <div class="flex items-center">
              <i class="pi pi-check-circle text-green-600 dark:text-green-400 mr-2"></i>
              <p class="text-green-800 dark:text-green-200">{{ successMessage }}</p>
            </div>
          </div>

          <!-- Actions -->
          <div class="flex justify-end space-x-3">
            <button
              type="button"
              @click="$emit('close')"
              class="px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-lg transition-colors duration-200"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="!isFormValid || isSubmitting"
              class="px-6 py-2 bg-primary-600 hover:bg-primary-700 disabled:bg-gray-400 dark:disabled:bg-gray-600 text-white font-medium rounded-lg transition-colors duration-200 flex items-center"
            >
              <i v-if="isSubmitting" class="pi pi-spin pi-spinner mr-2"></i>
              <i v-else class="pi pi-shopping-cart mr-2"></i>
              {{ isSubmitting ? 'Taking...' : 'Take Offer' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { useWalletDataService } from '@/features/walletConnect/services/WalletDataService'
  import { useOfferInspection } from '@/shared/composables/useOfferInspection'
  import {
    convertDexieOfferToAppOffer,
    getDexieStatusDescription,
  } from '@/shared/services/DexieDataService'
  import { formatAssetAmount } from '@/shared/utils/chia-units'
  import { isValidOfferString } from '@/shared/utils/offer-parser'
  import type { OfferAsset, OfferDetails } from '@/types/offer.types'
  import { computed, reactive, ref, watch } from 'vue'

  interface Emits {
    (e: 'close'): void
    (e: 'offer-taken', offer: OfferDetails): void
  }

  const emit = defineEmits<Emits>()

  // Services
  const walletDataService = useWalletDataService()
  const offerInspection = useOfferInspection()

  // Form state
  const form = reactive({
    offerString: '',
    fee: 0,
  })

  // UI state
  const isSubmitting = ref(false)
  const errorMessage = ref('')
  const successMessage = ref('')
  const offerPreview = ref<{
    assetsOffered?: OfferAsset[]
    assetsRequested?: OfferAsset[]
    creatorAddress?: string
    fee?: number
    status?: string
    dexieStatus?: number
  } | null>(null)
  const parseError = ref('')

  // Computed
  const isFormValid = computed(() => {
    return (
      form.offerString.trim().length > 0 &&
      form.fee >= 0 &&
      (!parseError.value || parseError.value.includes('validated'))
    )
  })

  // Methods
  const parseOffer = async (offerString: string) => {
    parseError.value = ''

    if (!offerString.trim()) {
      offerPreview.value = null
      return
    }

    if (!isValidOfferString(offerString)) {
      parseError.value = 'Invalid offer string format'
      offerPreview.value = null
      return
    }

    // Use Dexie to inspect the offer and get real asset details
    try {
      // First POST the offer to Dexie to get the Dexie ID
      const postResponse = await offerInspection.postOffer({
        offer: offerString.trim(),
        drop_only: false,
        claim_rewards: false,
      })

      if (postResponse && postResponse.success && postResponse.offer) {
        // The POST response contains the full offer data - use it directly
        const appOffer = convertDexieOfferToAppOffer(postResponse)

        offerPreview.value = {
          assetsOffered: appOffer.assetsOffered,
          assetsRequested: appOffer.assetsRequested,
          creatorAddress: appOffer.creatorAddress,
          fee: appOffer.fee,
          status: appOffer.status,
          dexieStatus: appOffer.dexieStatus,
        }
        parseError.value = ''
        return
      } else if (postResponse && postResponse.success && postResponse.id) {
        // Handle case where POST only returns ID (older API behavior)
        const dexieResponse = await offerInspection.inspectOffer(postResponse.id)

        if (dexieResponse && dexieResponse.success) {
          const appOffer = convertDexieOfferToAppOffer(dexieResponse)

          offerPreview.value = {
            assetsOffered: appOffer.assetsOffered,
            assetsRequested: appOffer.assetsRequested,
            creatorAddress: appOffer.creatorAddress,
            fee: appOffer.fee,
            status: appOffer.status,
            dexieStatus: appOffer.dexieStatus,
          }
          parseError.value = ''
          return
        }
      }
    } catch {
      parseError.value = 'Error inspecting offer on Dexie marketplace'
      offerPreview.value = null
      return
    }

    // If Dexie inspection failed, show basic validation
    parseError.value = 'Offer string validated - details will be confirmed by wallet'
    offerPreview.value = {
      assetsOffered: [],
      assetsRequested: [],
      creatorAddress: undefined,
      fee: undefined,
    }
  }

  const handleSubmit = async () => {
    errorMessage.value = ''
    successMessage.value = ''

    if (!isFormValid.value) {
      errorMessage.value = 'Please enter a valid offer string and fee'
      return
    }

    isSubmitting.value = true

    try {
      const result = await walletDataService.takeOffer({
        offer: form.offerString.trim(),
        fee: form.fee,
      })

      if (result?.success && result?.tradeId) {
        const takenOffer: OfferDetails = {
          id: Date.now().toString(),
          tradeId: result!.tradeId,
          offerString: form.offerString.trim(),
          status: 'pending',
          createdAt: new Date(),
          assetsOffered: offerPreview.value?.assetsOffered || [],
          assetsRequested: offerPreview.value?.assetsRequested || [],
          fee: offerPreview.value?.fee || form.fee,
          creatorAddress: offerPreview.value?.creatorAddress || 'unknown',
        }

        successMessage.value = 'Offer taken successfully!'
        emit('offer-taken', takenOffer)

        // Reset form
        form.offerString = ''
        form.fee = 0
        offerPreview.value = null
      } else {
        throw new Error('Failed to take offer')
      }
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error occurred'
      errorMessage.value = `Failed to take offer: ${errorMsg}`
    } finally {
      isSubmitting.value = false
    }
  }

  // Watch for offer string changes to update preview
  watch(
    () => form.offerString,
    async newValue => {
      await parseOffer(newValue)
    }
  )
</script>

// pengui/src/components/offers/TakeOfferModal.tsx
import Button from '@/components/shared/Button'
import Modal from '@/components/shared/Modal'
import { useOfferInspection } from '@/hooks/useOfferInspection'
import { useThemeClasses } from '@/hooks/useThemeClasses'
import { useTickerData } from '@/hooks/useTickerData'
import { useTakeOffer } from '@/hooks/useWalletQueries'
import type { DexiePostOfferResponse } from '@/lib/dexie/DexieRepository'
import { calculateOfferState } from '@/lib/dexie/DexieRepository'
import { formatAssetAmount, getMinimumFeeInXch } from '@/lib/utils/chia-units'
import { getDexieStatusDescription, validateOfferString } from '@/lib/utils/offerUtils'
import type { OfferAsset, OfferDetails } from '@/types/offer.types'
import { convertOfferStateToStatus } from '@/types/offer.types'
import { Loader2, ShoppingCart, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'

interface TakeOfferModalProps {
  onClose: () => void
  onOfferTaken?: (offer: OfferDetails) => void
}

/**
 * Convert Dexie offer to app offer format
 */
function convertDexieOfferToAppOffer(dexieResponse: DexiePostOfferResponse): {
  assetsOffered: OfferAsset[]
  assetsRequested: OfferAsset[]
  creatorAddress?: string
  fee: number
  status: string
  dexieStatus: string
} {
  if (!dexieResponse.offer) {
    return {
      assetsOffered: [],
      assetsRequested: [],
      fee: 0,
      status: 'unknown',
      dexieStatus: 'Unknown',
    }
  }

  const offer = dexieResponse.offer
  const calculatedState = calculateOfferState(offer)

  // Convert Dexie assets to app assets
  // DexieAsset has: id (asset ID), code, name, amount
  // If id is empty or "XCH", it's XCH, otherwise it's a CAT token
  // For XCH assets, assetId should be empty string (as per BaseAsset interface requirement)
  const assetsOffered: OfferAsset[] = (offer.offered || []).map((asset) => {
    const isXch = !asset.id || asset.id === 'XCH'
    return {
      amount: asset.amount,
      assetId: isXch ? '' : asset.id, // Empty string for XCH, asset ID for CAT
      type: (isXch ? 'xch' : 'cat') as 'xch' | 'cat',
      symbol: asset.code || undefined, // Use code as symbol
    }
  })

  const assetsRequested: OfferAsset[] = (offer.requested || []).map((asset) => {
    const isXch = !asset.id || asset.id === 'XCH'
    return {
      amount: asset.amount,
      assetId: isXch ? '' : asset.id, // Empty string for XCH, asset ID for CAT
      type: (isXch ? 'xch' : 'cat') as 'xch' | 'cat',
      symbol: asset.code || undefined, // Use code as symbol
    }
  })

  return {
    assetsOffered,
    assetsRequested,
    creatorAddress: undefined, // Dexie doesn't provide this directly
    fee: offer.fees ? offer.fees / 1_000_000_000_000 : 0, // Convert mojos to XCH
    status: convertOfferStateToStatus(calculatedState),
    dexieStatus: calculatedState,
  }
}

export default function TakeOfferModal({ onClose, onOfferTaken }: TakeOfferModalProps) {
  const { t } = useThemeClasses()
  const { postOffer, isPosting } = useOfferInspection()
  const takeOfferMutation = useTakeOffer()
  const { getCatTokenInfo } = useTickerData()

  // Form state
  const [offerString, setOfferString] = useState('')
  const [fee, setFee] = useState(getMinimumFeeInXch())
  const [feeInput, setFeeInput] = useState(getMinimumFeeInXch().toString())

  // UI state
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')
  const [parseError, setParseError] = useState('')
  const [offerPreview, setOfferPreview] = useState<{
    assetsOffered?: OfferAsset[]
    assetsRequested?: OfferAsset[]
    creatorAddress?: string
    fee?: number
    status?: string
    dexieStatus?: string
  } | null>(null)

  // Parse offer when string changes
  useEffect(() => {
    const parseOffer = async () => {
      setParseError('')
      setOfferPreview(null)

      if (!offerString.trim()) {
        return
      }

      if (!validateOfferString(offerString)) {
        setParseError('Invalid offer string format')
        return
      }

      // Use Dexie to inspect the offer and get real asset details
      try {
        const postResponse = await postOffer({
          offer: offerString.trim(),
          drop_only: false,
          claim_rewards: false,
        })

        if (postResponse && postResponse.success && postResponse.offer) {
          // The POST response contains the full offer data - use it directly
          const appOffer = convertDexieOfferToAppOffer(postResponse)

          // Enrich assets with ticker symbols
          const enrichedAssetsOffered = await Promise.all(
            appOffer.assetsOffered.map(async (asset) => {
              if (asset.assetId) {
                const tickerInfo = await getCatTokenInfo(asset.assetId)
                return {
                  ...asset,
                  symbol: tickerInfo?.ticker || undefined,
                }
              }
              return asset
            })
          )

          const enrichedAssetsRequested = await Promise.all(
            appOffer.assetsRequested.map(async (asset) => {
              if (asset.assetId) {
                const tickerInfo = await getCatTokenInfo(asset.assetId)
                return {
                  ...asset,
                  symbol: tickerInfo?.ticker || undefined,
                }
              }
              return asset
            })
          )

          setOfferPreview({
            assetsOffered: enrichedAssetsOffered,
            assetsRequested: enrichedAssetsRequested,
            creatorAddress: appOffer.creatorAddress,
            fee: appOffer.fee,
            status: appOffer.status,
            dexieStatus: appOffer.dexieStatus,
          })
          setParseError('')
        } else if (postResponse && postResponse.success && postResponse.id) {
          // Handle case where POST only returns ID (older API behavior)
          // For now, just show basic validation
          setParseError('Offer string validated - details will be confirmed by wallet')
          setOfferPreview({
            assetsOffered: [],
            assetsRequested: [],
            creatorAddress: undefined,
            fee: undefined,
          })
        }
      } catch {
        setParseError('Error inspecting offer on Dexie marketplace')
        setOfferPreview(null)
      }
    }

    // Debounce parsing
    const timeoutId = setTimeout(() => {
      parseOffer()
    }, 500)

    return () => clearTimeout(timeoutId)
  }, [offerString, postOffer, getCatTokenInfo])

  // Handle fee input
  const handleFeeChange = useCallback((value: string) => {
    setFeeInput(value)
    const numValue = parseFloat(value)
    if (!isNaN(numValue) && numValue >= 0) {
      setFee(numValue)
    }
  }, [])

  const isFormValid =
    offerString.trim().length > 0 && fee >= 0 && (!parseError || parseError.includes('validated'))

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault()
      setErrorMessage('')
      setSuccessMessage('')

      if (!isFormValid) {
        setErrorMessage('Please enter a valid offer string and fee')
        return
      }

      setIsSubmitting(true)

      try {
        const result = await takeOfferMutation.mutateAsync({
          offer: offerString.trim(),
          fee: fee,
        })

        if (result && result.success && result.tradeId) {
          const takenOffer: OfferDetails = {
            id: Date.now().toString(),
            tradeId: result.tradeId,
            offerString: offerString.trim(),
            status: 'pending',
            createdAt: new Date(),
            assetsOffered: offerPreview?.assetsOffered || [],
            assetsRequested: offerPreview?.assetsRequested || [],
            fee: offerPreview?.fee || fee,
            creatorAddress: offerPreview?.creatorAddress || 'unknown',
          }

          setSuccessMessage('Offer taken successfully!')
          onOfferTaken?.(takenOffer)

          // Reset form after a short delay
          setTimeout(() => {
            setOfferString('')
            setFee(getMinimumFeeInXch())
            setFeeInput(getMinimumFeeInXch().toString())
            setOfferPreview(null)
            setSuccessMessage('')
            onClose()
          }, 1500)
        } else {
          throw new Error('Failed to take offer')
        }
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error occurred'
        setErrorMessage(`Failed to take offer: ${errorMsg}`)
      } finally {
        setIsSubmitting(false)
      }
    },
    [offerString, fee, isFormValid, takeOfferMutation, offerPreview, onOfferTaken, onClose]
  )

  const getTickerSymbol = useCallback(
    (assetId: string | undefined, symbol?: string) => {
      if (symbol) return symbol
      if (!assetId) return 'XCH'
      const tickerInfo = getCatTokenInfo(assetId)
      return tickerInfo?.ticker || assetId.slice(0, 8)
    },
    [getCatTokenInfo]
  )

  return (
    <Modal onClose={onClose} maxWidth="max-w-lg" closeOnOverlayClick={!isSubmitting}>
      <div className="p-4">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <h2 className={`text-lg font-semibold ${t.text}`}>Take Offer</h2>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className={`${t.textSecondary} hover:${t.text} transition-colors disabled:opacity-50`}
          >
            <X size={18} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Offer String Input */}
          <div>
            <label className={`block text-xs font-medium ${t.text} mb-1.5`}>Offer String</label>
            <textarea
              value={offerString}
              onChange={(e) => setOfferString(e.target.value)}
              rows={4}
              placeholder="Paste the offer string here..."
              className={`w-full px-2 py-1.5 border rounded-lg resize-none text-xs font-mono ${t.input} ${t.border} backdrop-blur-xl`}
              required
              disabled={isSubmitting}
            />
            <p className={`mt-1 text-xs ${t.textSecondary}`}>
              Paste the complete offer string from the offer creator
            </p>
            {parseError && (
              <p
                className={`mt-1 text-xs ${
                  parseError.includes('validated')
                    ? 'text-blue-600 dark:text-blue-400'
                    : 'text-red-600 dark:text-red-400'
                }`}
              >
                {parseError}
              </p>
            )}
            {isPosting && (
              <div className="mt-2 flex items-center">
                <Loader2 size={12} className="animate-spin text-blue-600 dark:text-blue-400 mr-2" />
                <p className="text-xs text-blue-600 dark:text-blue-400">
                  Processing offer with Dexie marketplace...
                </p>
              </div>
            )}
          </div>

          {/* Transaction Fee */}
          <div>
            <label className={`block text-xs font-medium ${t.text} mb-1.5`}>
              Transaction Fee (XCH)
            </label>
            <input
              type="number"
              value={feeInput}
              onChange={(e) => handleFeeChange(e.target.value)}
              step="0.000001"
              min="0"
              placeholder={getMinimumFeeInXch().toString()}
              className={`w-full px-2 py-1.5 border rounded-lg text-xs ${t.input} ${t.border} backdrop-blur-xl`}
              disabled={isSubmitting}
            />
            <p className={`mt-1 text-xs ${t.textSecondary}`}>
              Fee can be 0 for free transactions (minimum: {getMinimumFeeInXch()} XCH)
            </p>
          </div>

          {/* Offer Preview */}
          {offerPreview && (
            <div className={`p-3 rounded-lg ${t.cardHover} backdrop-blur-xl border ${t.border}`}>
              <h4 className={`text-xs font-medium ${t.text} mb-2`}>Offer Preview</h4>
              <div className="space-y-1.5 text-xs">
                <div className="flex justify-between">
                  <span className={t.textSecondary}>You will receive:</span>
                  <span className={t.text}>
                    {offerPreview.assetsOffered && offerPreview.assetsOffered.length > 0
                      ? offerPreview.assetsOffered
                          .map(
                            (a) =>
                              `${formatAssetAmount(a.amount, a.type)} ${getTickerSymbol(a.assetId, a.symbol)}`
                          )
                          .join(', ')
                      : 'Assets from offer'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className={t.textSecondary}>You will pay:</span>
                  <span className={t.text}>
                    {offerPreview.assetsRequested && offerPreview.assetsRequested.length > 0
                      ? offerPreview.assetsRequested
                          .map(
                            (a) =>
                              `${formatAssetAmount(a.amount, a.type)} ${getTickerSymbol(a.assetId, a.symbol)}`
                          )
                          .join(', ')
                      : 'Assets to offer creator'}
                  </span>
                </div>
                <div className={`flex justify-between border-t ${t.border} pt-1.5 mt-1.5`}>
                  <span className={`font-medium ${t.text}`}>Fee:</span>
                  <span className={`font-medium ${t.text}`}>
                    {offerPreview.fee !== undefined ? offerPreview.fee : fee} XCH
                  </span>
                </div>
                {offerPreview.dexieStatus && (
                  <div className={`flex justify-between border-t ${t.border} pt-1.5 mt-1.5`}>
                    <span className={`font-medium ${t.text}`}>Status:</span>
                    <span className={`font-medium ${t.text}`}>
                      {getDexieStatusDescription(offerPreview.dexieStatus)}
                    </span>
                  </div>
                )}
                {offerPreview.creatorAddress && (
                  <div className={`flex justify-between border-t ${t.border} pt-1.5 mt-1.5`}>
                    <span className={`font-medium ${t.text}`}>Creator:</span>
                    <span className={`font-medium ${t.text} text-xs font-mono`}>
                      {offerPreview.creatorAddress.slice(0, 8)}...
                      {offerPreview.creatorAddress.slice(-8)}
                    </span>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Error/Success Messages */}
          {errorMessage && (
            <div
              className={`p-2 rounded-lg border ${t.border} backdrop-blur-xl bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800`}
            >
              <p className="text-xs text-red-700 dark:text-red-300">{errorMessage}</p>
            </div>
          )}

          {successMessage && (
            <div
              className={`p-2 rounded-lg border ${t.border} backdrop-blur-xl bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800`}
            >
              <p className="text-xs text-green-700 dark:text-green-300">{successMessage}</p>
            </div>
          )}

          {/* Actions */}
          <div className="flex flex-wrap justify-end gap-2 pt-2 border-t border-white/20 dark:border-white/10">
            <Button type="button" onClick={onClose} variant="secondary" disabled={isSubmitting}>
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={!isFormValid || isSubmitting}
              variant="success"
              icon={isSubmitting ? undefined : ShoppingCart}
            >
              {isSubmitting ? (
                <>
                  <Loader2 size={12} className="animate-spin" />
                  Taking...
                </>
              ) : (
                'Take Offer'
              )}
            </Button>
          </div>
        </form>
      </div>
    </Modal>
  )
}
