// pengui/src/features/trading/ui/modals/CreateOfferModal.tsx
'use client'

import { toWalletAssets } from '@/entities/asset'
import type { AssetAmount, OfferDetails } from '@/entities/offer'
import { useCreateOffer, useWalletAddress } from '@/features/wallet'
import { useAmountInput, useThemeClasses } from '@/shared/hooks'
import { convertToSmallestUnit } from '@/shared/lib/utils/chia-units'
import Button from '@/shared/ui/Button'
import Modal from '@/shared/ui/Modal'
import { Loader2, Plus, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useOfferStorage } from '@/features/offers/model/useOfferStorage'
import AssetSelector, { type ExtendedAsset as ExtendedOfferAsset } from '@/shared/ui/AssetSelector'

interface CreateOfferModalProps {
  onClose: () => void
  onOfferCreated: (offer: OfferDetails) => void
}

export default function CreateOfferModal({ onClose, onOfferCreated }: CreateOfferModalProps) {
  const { t, isDark } = useThemeClasses()
  const createOfferMutation = useCreateOffer()
  const offerStorage = useOfferStorage()
  const { data: walletAddress } = useWalletAddress()

  // Form state with extended asset types for UI
  interface ExtendedCreateOfferForm {
    assetsOffered: ExtendedOfferAsset[]
    assetsRequested: ExtendedOfferAsset[]
    fee: AssetAmount
    memo?: string
    expirationEnabled?: boolean
    expirationDays?: number
    expirationHours?: number
    expirationMinutes?: number
  }

  const [form, setForm] = useState<ExtendedCreateOfferForm>({
    assetsOffered: [],
    assetsRequested: [],
    fee: 0,
    memo: '',
    expirationEnabled: false,
    expirationDays: 1,
    expirationHours: 0,
    expirationMinutes: 0,
  })

  // Fee input composable
  const feeInput = useAmountInput({
    value: form.fee,
    assetType: 'xch',
    onChange: (value) => {
      setForm((prev) => ({ ...prev, fee: value }))
    },
  })

  // UI state
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')

  // Initialize with one asset in each section
  useEffect(() => {
    setForm((prev) => ({
      ...prev,
      assetsOffered: [
        {
          assetId: '',
          amount: 0,
          type: 'xch',
          symbol: '',
        },
      ],
      assetsRequested: [
        {
          assetId: '',
          amount: 0,
          type: 'xch',
          symbol: '',
        },
      ],
    }))
  }, [])

  // Computed
  const isFormValid = useMemo(() => {
    return (
      form.assetsOffered.length > 0 &&
      form.assetsRequested.length > 0 &&
      form.assetsOffered.every(
        (asset) => asset.amount >= 0 && (asset.type === 'xch' || asset.assetId)
      ) &&
      form.assetsRequested.every(
        (asset) => asset.amount >= 0 && (asset.type === 'xch' || asset.assetId)
      ) &&
      form.fee >= 0
    )
  }, [form])

  // Methods
  const addOfferedAsset = useCallback(() => {
    setForm((prev) => ({
      ...prev,
      assetsOffered: [
        ...prev.assetsOffered,
        {
          assetId: '',
          amount: 0,
          type: 'xch',
          symbol: '',
        },
      ],
    }))
  }, [])

  const removeOfferedAsset = useCallback((index: number) => {
    setForm((prev) => ({
      ...prev,
      assetsOffered: prev.assetsOffered.filter((_, i) => i !== index),
    }))
  }, [])

  const updateOfferedAsset = useCallback((index: number, asset: ExtendedOfferAsset) => {
    setForm((prev) => ({
      ...prev,
      assetsOffered: prev.assetsOffered.map((a, i) => (i === index ? asset : a)),
    }))
  }, [])

  const addRequestedAsset = useCallback(() => {
    setForm((prev) => ({
      ...prev,
      assetsRequested: [
        ...prev.assetsRequested,
        {
          assetId: '',
          amount: 0,
          type: 'xch',
          symbol: '',
        },
      ],
    }))
  }, [])

  const removeRequestedAsset = useCallback((index: number) => {
    setForm((prev) => ({
      ...prev,
      assetsRequested: prev.assetsRequested.filter((_, i) => i !== index),
    }))
  }, [])

  const updateRequestedAsset = useCallback((index: number, asset: ExtendedOfferAsset) => {
    setForm((prev) => ({
      ...prev,
      assetsRequested: prev.assetsRequested.map((a, i) => (i === index ? asset : a)),
    }))
  }, [])

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault()
      setErrorMessage('')
      setSuccessMessage('')

      if (!isFormValid) {
        setErrorMessage('Please fill in all required fields')
        return
      }

      setIsSubmitting(true)

      try {
        // Convert form assets to the format expected by the wallet
        // Use utility function to ensure proper asset ID mapping
        const offerAssets = toWalletAssets(
          form.assetsOffered.map((asset) => ({
            ...asset,
            amount: Number(asset.amount) || 0,
          })),
          convertToSmallestUnit
        )

        const requestAssets = toWalletAssets(
          form.assetsRequested.map((asset) => ({
            ...asset,
            amount: Number(asset.amount) || 0,
          })),
          convertToSmallestUnit
        )

        const result = await createOfferMutation.mutateAsync({
          walletId: 1,
          offerAssets,
          requestAssets,
          fee: convertToSmallestUnit(Number(form.fee) || 0, 'xch'), // Fee is always in XCH
        })

        if (!result || !result.offer) {
          throw new Error('Wallet did not return a valid offer string')
        }

        const newOffer: OfferDetails = {
          id: result?.id || Date.now().toString(),
          tradeId: result?.tradeId || result?.id || 'unknown',
          offerString: result?.offer || '',
          status: 'active',
          createdAt: new Date(),
          assetsOffered: form.assetsOffered.map((asset) => ({
            assetId: asset.assetId || '',
            amount: Number(asset.amount) || 0, // Ensure amount is always a number
            type: asset.type,
            symbol: asset.symbol || asset.type.toUpperCase(),
          })),
          assetsRequested: form.assetsRequested.map((asset) => ({
            assetId: asset.assetId || '',
            amount: Number(asset.amount) || 0, // Ensure amount is always a number
            type: asset.type,
            symbol: asset.symbol || asset.type.toUpperCase(),
          })),
          fee: Number(form.fee) || 0, // Ensure fee is always a number
          creatorAddress: walletAddress?.address || 'unknown',
        }

        // Save offer to IndexedDB
        await offerStorage.saveOffer(newOffer, true) // true = isLocal

        setSuccessMessage('Offer created successfully!')
        onOfferCreated(newOffer)

        // Reset form
        setForm({
          assetsOffered: [],
          assetsRequested: [],
          fee: 0,
          memo: '',
          expirationEnabled: false,
          expirationDays: 1,
          expirationHours: 0,
          expirationMinutes: 0,
        })
        feeInput.reset()
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error occurred'
        setErrorMessage(`Failed to create offer: ${errorMsg}`)
      } finally {
        setIsSubmitting(false)
      }
    },
    [form, isFormValid, createOfferMutation, offerStorage, walletAddress, onOfferCreated, feeInput]
  )

  return (
    <Modal onClose={onClose} maxWidth="max-w-5xl">
      <div className="p-4">
        {/* Header */}
        <div className="flex items-center justify-between mb-3">
          <h2 className={`text-lg font-semibold ${t.text}`}>New Offer</h2>
          <button
            onClick={onClose}
            className={`${t.textSecondary} hover:${t.text} transition-colors`}
          >
            <X size={18} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Two Column Layout: Offered | Requested */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {/* Offered Section */}
            <div className="space-y-3">
              <div>
                <h3 className={`text-base font-medium ${t.text} mb-0.5`}>Offered</h3>
                <p className={`text-xs ${t.textSecondary}`}>Add the assets you are offering.</p>
              </div>
              <div className="space-y-2">
                {form.assetsOffered.map((asset, index) => (
                  <AssetSelector
                    key={`offered-${index}`}
                    asset={{
                      ...asset,
                      searchQuery: asset.searchQuery || '',
                      showDropdown: asset.showDropdown || false,
                    }}
                    onUpdate={(updatedAsset) => updateOfferedAsset(index, updatedAsset)}
                    onRemove={() => removeOfferedAsset(index)}
                  />
                ))}
                <Button
                  type="button"
                  onClick={addOfferedAsset}
                  variant="secondary"
                  icon={Plus}
                  className="w-full"
                >
                  Add Asset
                </Button>
              </div>
            </div>

            {/* Requested Section */}
            <div className="space-y-3">
              <div>
                <h3 className={`text-base font-medium ${t.text} mb-0.5`}>Requested</h3>
                <p className={`text-xs ${t.textSecondary}`}>Add the assets you are requesting.</p>
              </div>
              <div className="space-y-2">
                {form.assetsRequested.map((asset, index) => (
                  <AssetSelector
                    key={`requested-${index}`}
                    asset={{
                      ...asset,
                      searchQuery: asset.searchQuery || '',
                      showDropdown: asset.showDropdown || false,
                    }}
                    onUpdate={(updatedAsset) => updateRequestedAsset(index, updatedAsset)}
                    onRemove={() => removeRequestedAsset(index)}
                  />
                ))}
                <Button
                  type="button"
                  onClick={addRequestedAsset}
                  variant="secondary"
                  icon={Plus}
                  className="w-full"
                >
                  Add Asset
                </Button>
              </div>
            </div>
          </div>

          {/* Bottom Section: Fee and Settings */}
          <div className={`border-t ${t.border} pt-3`}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 items-start">
              <div>
                <label className={`block text-xs font-medium ${t.textSecondary} mb-1.5`}>
                  Network Fee
                </label>
                <div className="flex items-center gap-2 mt-2.5">
                  <input
                    type="text"
                    inputMode="decimal"
                    pattern="[0-9]*\.?[0-9]*"
                    autoComplete="off"
                    spellCheck={false}
                    value={feeInput.value}
                    onChange={feeInput.onChange}
                    onBlur={feeInput.onBlur}
                    placeholder={feeInput.placeholder}
                    className={`flex-1 px-2 py-1.5 text-xs border ${t.border} rounded-lg backdrop-blur-xl ${t.input} ${t.text}`}
                  />
                  <span className={`text-xs ${t.textSecondary} whitespace-nowrap`}>XCH</span>
                </div>
              </div>
              <div className="min-h-[60px]">
                <div className="flex items-center justify-between mb-1.5">
                  <label className={`block text-xs font-medium ${t.textSecondary}`}>
                    Expiring offer
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      setForm((prev) => ({
                        ...prev,
                        expirationEnabled: !prev.expirationEnabled,
                      }))
                    }}
                    className={`relative inline-flex h-5 w-9 items-center rounded-full backdrop-blur-3xl transition-all duration-300 focus:outline-none focus:ring-2 ${t.focusRing} overflow-hidden ${
                      isDark
                        ? form.expirationEnabled
                          ? 'bg-gradient-to-r from-white/5 via-white/10 to-white/5 border border-white/10 shadow-lg shadow-amber-500/20'
                          : 'bg-gradient-to-r from-white/5 via-white/10 to-white/5 border border-white/10 shadow-lg'
                        : form.expirationEnabled
                          ? 'bg-gradient-to-r from-white/20 via-white/30 to-white/20 border border-white/30 shadow-lg shadow-slate-900/20'
                          : 'bg-gradient-to-r from-white/20 via-white/30 to-white/20 border border-white/30 shadow-lg'
                    }`}
                    aria-label="Toggle expiration"
                  >
                    {/* Glass reflection effect */}
                    <div className="absolute inset-0 bg-gradient-to-b from-white/20 to-transparent opacity-50 rounded-full pointer-events-none" />
                    <span
                      className={`relative inline-block h-3 w-3 transform rounded-full backdrop-blur-3xl transition-all duration-300 shadow-lg ${
                        form.expirationEnabled
                          ? isDark
                            ? 'translate-x-[20px] bg-gradient-to-br from-white/30 via-white/20 to-white/10 border border-white/40'
                            : 'translate-x-[20px] bg-gradient-to-br from-white/50 via-white/40 to-white/30 border border-white/60'
                          : isDark
                            ? 'translate-x-0.5 bg-gradient-to-br from-white/30 via-white/20 to-white/10 border border-white/40'
                            : 'translate-x-0.5 bg-gradient-to-br from-white/50 via-white/40 to-white/30 border border-white/60'
                      } flex items-center justify-center`}
                    >
                      {/* Inner glass highlight */}
                      <div className="absolute inset-0 bg-gradient-to-br from-white/40 to-transparent rounded-full opacity-60" />
                    </span>
                  </button>
                </div>
                {/* Always render container with fixed height to prevent layout shift */}
                <div className="h-[52px] relative">
                  <div
                    className={`absolute inset-0 grid grid-cols-3 gap-2 transition-all duration-300 ${
                      form.expirationEnabled
                        ? 'opacity-100 translate-y-0 pointer-events-auto'
                        : 'opacity-0 -translate-y-2 pointer-events-none'
                    }`}
                  >
                    <div>
                      <input
                        type="number"
                        min="0"
                        value={form.expirationDays || 0}
                        onChange={(e) => {
                          const value = e.target.value === '' ? 0 : parseInt(e.target.value, 10)
                          setForm((prev) => ({
                            ...prev,
                            expirationDays: isNaN(value) ? 0 : Math.max(0, value),
                          }))
                        }}
                        placeholder="0"
                        disabled={!form.expirationEnabled}
                        className={`w-full px-2 py-1.5 text-xs border ${t.border} rounded-lg backdrop-blur-xl ${t.input} ${t.text} disabled:opacity-50 disabled:cursor-not-allowed`}
                      />
                      <label className={`block text-[10px] ${t.textSecondary} mt-1 text-center`}>
                        Days
                      </label>
                    </div>
                    <div>
                      <input
                        type="number"
                        min="0"
                        max="23"
                        value={form.expirationHours || 0}
                        onChange={(e) => {
                          const value = e.target.value === '' ? 0 : parseInt(e.target.value, 10)
                          setForm((prev) => ({
                            ...prev,
                            expirationHours: isNaN(value) ? 0 : Math.max(0, Math.min(23, value)),
                          }))
                        }}
                        placeholder="0"
                        disabled={!form.expirationEnabled}
                        className={`w-full px-2 py-1.5 text-xs border ${t.border} rounded-lg backdrop-blur-xl ${t.input} ${t.text} disabled:opacity-50 disabled:cursor-not-allowed`}
                      />
                      <label className={`block text-[10px] ${t.textSecondary} mt-1 text-center`}>
                        Hours
                      </label>
                    </div>
                    <div>
                      <input
                        type="number"
                        min="0"
                        max="59"
                        value={form.expirationMinutes || 0}
                        onChange={(e) => {
                          const value = e.target.value === '' ? 0 : parseInt(e.target.value, 10)
                          setForm((prev) => ({
                            ...prev,
                            expirationMinutes: isNaN(value) ? 0 : Math.max(0, Math.min(59, value)),
                          }))
                        }}
                        placeholder="0"
                        disabled={!form.expirationEnabled}
                        className={`w-full px-2 py-1.5 text-xs border ${t.border} rounded-lg backdrop-blur-xl ${t.input} ${t.text} disabled:opacity-50 disabled:cursor-not-allowed`}
                      />
                      <label className={`block text-[10px] ${t.textSecondary} mt-1 text-center`}>
                        Minutes
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Error/Success Messages */}
          {errorMessage && (
            <div
              className={`p-3 backdrop-blur-xl rounded-lg border ${isDark ? 'bg-red-900/20 border-red-800/40' : 'bg-red-50/80 border-red-200/60'}`}
            >
              <p className={`text-xs ${isDark ? 'text-red-200' : 'text-red-800'}`}>
                {errorMessage}
              </p>
            </div>
          )}

          {successMessage && (
            <div
              className={`p-3 backdrop-blur-xl rounded-lg border ${isDark ? 'bg-green-900/20 border-green-800/40' : 'bg-green-50/80 border-green-200/60'}`}
            >
              <p className={`text-xs ${isDark ? 'text-green-200' : 'text-green-800'}`}>
                {successMessage}
              </p>
            </div>
          )}

          {/* Actions */}
          <div className={`flex justify-end gap-2 pt-3 border-t ${t.border}`}>
            <Button type="button" onClick={onClose} variant="secondary">
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={!isFormValid || isSubmitting}
              variant="primary"
              icon={isSubmitting ? undefined : Plus}
            >
              {isSubmitting ? (
                <>
                  <Loader2 size={14} strokeWidth={2.5} className="animate-spin" />
                  Creating...
                </>
              ) : (
                'Create Offer'
              )}
            </Button>
          </div>
        </form>
      </div>
    </Modal>
  )
}

// src/components/Offers/CreateOfferModal.vue
<template>
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
    <div
      class="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
    >
      <div class="p-6">
        <!-- Header -->
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-xl font-semibold text-gray-900 dark:text-white">Create Offer</h2>
          <button
            @click="$emit('close')"
            class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
          >
            <i class="pi pi-times text-xl"></i>
          </button>
        </div>

        <!-- Form -->
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Assets Offered Section -->
          <div>
            <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-4">
              Assets I'm Offering
            </h3>
            <div class="space-y-3">
              <div
                v-for="(asset, index) in form.assetsOffered"
                :key="`offered-${index}`"
                class="flex items-center space-x-3 p-3 border border-gray-200 dark:border-gray-600 rounded-lg"
              >
                <div class="flex-1">
                  <select
                    v-model="asset.type"
                    @change="clearAssetSelection(asset)"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  >
                    <option value="xch">XCH (Chia)</option>
                    <option value="cat">CAT Token</option>
                    <option value="nft">NFT</option>
                  </select>
                </div>
                <div class="flex-1">
                  <!-- XCH Asset (no selection needed) -->
                  <div
                    v-if="asset.type === 'xch'"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-400 text-sm"
                  >
                    XCH (Chia)
                  </div>

                  <!-- CAT Token Searchable Dropdown -->
                  <div v-else-if="asset.type === 'cat'" class="relative flex-2">
                    <input
                      v-model="asset.searchQuery"
                      @focus="asset.showDropdown = true"
                      @blur="setTimeout(() => (asset.showDropdown = false), 200)"
                      type="text"
                      placeholder="Search CAT tokens..."
                      class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                    />

                    <!-- Dropdown -->
                    <div
                      v-if="asset.showDropdown && filteredCatTokens(asset.searchQuery).length > 0"
                      class="absolute z-10 w-full mt-1 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg shadow-lg max-h-48 overflow-y-auto"
                    >
                      <div
                        v-for="token in filteredCatTokens(asset.searchQuery)"
                        :key="token.assetId"
                        @click="selectCatToken(asset, token)"
                        class="px-3 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 cursor-pointer text-sm"
                      >
                        <div class="font-medium text-gray-900 dark:text-white">
                          {{ token.ticker }}
                        </div>
                      </div>
                    </div>
                  </div>

                  <!-- NFT Asset ID Input -->
                  <input
                    v-else
                    v-model="asset.assetId"
                    type="text"
                    placeholder="NFT Asset ID"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  />
                </div>
                <div class="flex-1">
                  <input
                    v-model.number="asset.amount"
                    type="number"
                    step="0.000001"
                    min="0"
                    placeholder="Amount"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  />
                </div>
                <div class="flex-1">
                  <!-- Auto-populated symbol for CAT tokens -->
                  <div
                    v-if="asset.type === 'cat' && asset.assetId"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-100 dark:bg-gray-600 text-gray-700 dark:text-gray-300 text-sm"
                  >
                    {{ getCatTokenInfo(asset.assetId).ticker }}
                  </div>
                  <!-- Manual symbol input for other types -->
                  <input
                    v-else
                    v-model="asset.symbol"
                    type="text"
                    placeholder="Symbol (optional)"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  />
                </div>
                <button
                  @click="removeOfferedAsset(index)"
                  type="button"
                  class="text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300"
                >
                  <i class="pi pi-trash"></i>
                </button>
              </div>
              <button
                @click="addOfferedAsset"
                type="button"
                class="w-full py-2 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg text-gray-600 dark:text-gray-400 hover:border-primary-500 dark:hover:border-primary-400 hover:text-primary-600 dark:hover:text-primary-400 transition-colors"
              >
                <i class="pi pi-plus mr-2"></i>
                Add Asset
              </button>
            </div>
          </div>

          <!-- Assets Requested Section -->
          <div>
            <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-4">Assets I Want</h3>
            <div class="space-y-3">
              <div
                v-for="(asset, index) in form.assetsRequested"
                :key="`requested-${index}`"
                class="flex items-center space-x-3 p-3 border border-gray-200 dark:border-gray-600 rounded-lg"
              >
                <div class="flex-1">
                  <select
                    v-model="asset.type"
                    @change="clearAssetSelection(asset)"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  >
                    <option value="xch">XCH (Chia)</option>
                    <option value="cat">CAT Token</option>
                    <option value="nft">NFT</option>
                  </select>
                </div>
                <div class="flex-1">
                  <!-- XCH Asset (no selection needed) -->
                  <div
                    v-if="asset.type === 'xch'"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-400 text-sm"
                  >
                    XCH (Chia)
                  </div>

                  <!-- CAT Token Searchable Dropdown -->
                  <div v-else-if="asset.type === 'cat'" class="relative flex-2">
                    <input
                      v-model="asset.searchQuery"
                      @focus="asset.showDropdown = true"
                      @blur="setTimeout(() => (asset.showDropdown = false), 200)"
                      type="text"
                      placeholder="Search CAT tokens..."
                      class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                    />

                    <!-- Dropdown -->
                    <div
                      v-if="asset.showDropdown && filteredCatTokens(asset.searchQuery).length > 0"
                      class="absolute z-10 w-full mt-1 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg shadow-lg max-h-48 overflow-y-auto"
                    >
                      <div
                        v-for="token in filteredCatTokens(asset.searchQuery)"
                        :key="token.assetId"
                        @click="selectCatToken(asset, token)"
                        class="px-3 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 cursor-pointer text-sm"
                      >
                        <div class="font-medium text-gray-900 dark:text-white">
                          {{ token.ticker }}
                        </div>
                      </div>
                    </div>
                  </div>

                  <!-- NFT Asset ID Input -->
                  <input
                    v-else
                    v-model="asset.assetId"
                    type="text"
                    placeholder="NFT Asset ID"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  />
                </div>
                <div class="flex-1">
                  <input
                    v-model.number="asset.amount"
                    type="number"
                    step="0.000001"
                    min="0"
                    placeholder="Amount"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  />
                </div>
                <div class="flex-1">
                  <!-- Auto-populated symbol for CAT tokens -->
                  <div
                    v-if="asset.type === 'cat' && asset.assetId"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-100 dark:bg-gray-600 text-gray-700 dark:text-gray-300 text-sm"
                  >
                    {{ getCatTokenInfo(asset.assetId).ticker }}
                  </div>
                  <!-- Manual symbol input for other types -->
                  <input
                    v-else
                    v-model="asset.symbol"
                    type="text"
                    placeholder="Symbol (optional)"
                    class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  />
                </div>
                <button
                  @click="removeRequestedAsset(index)"
                  type="button"
                  class="text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300"
                >
                  <i class="pi pi-trash"></i>
                </button>
              </div>
              <button
                @click="addRequestedAsset"
                type="button"
                class="w-full py-2 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg text-gray-600 dark:text-gray-400 hover:border-primary-500 dark:hover:border-primary-400 hover:text-primary-600 dark:hover:text-primary-400 transition-colors"
              >
                <i class="pi pi-plus mr-2"></i>
                Add Asset
              </button>
            </div>
          </div>

          <!-- Offer Details -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Transaction Fee
              </label>
              <input
                v-model.number="form.fee"
                type="number"
                step="0.000001"
                min="0"
                placeholder="0.000001"
                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Expiration (hours)
              </label>
              <input
                v-model.number="form.expirationHours"
                type="number"
                min="1"
                max="168"
                placeholder="24"
                class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Memo (optional)
            </label>
            <textarea
              v-model="form.memo"
              rows="3"
              placeholder="Add a description for this offer..."
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white resize-none"
            ></textarea>
          </div>

          <!-- Offer Summary -->
          <div
            v-if="form.assetsOffered.length > 0 && form.assetsRequested.length > 0"
            class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4"
          >
            <h4 class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Offer Summary</h4>
            <div class="space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-gray-600 dark:text-gray-400">Offering:</span>
                <span class="text-gray-900 dark:text-white">
                  {{
                    form.assetsOffered
                      .map(
                        a =>
                          `${formatAssetAmount(a.amount, a.type)} ${a.symbol || a.type.toUpperCase()}`
                      )
                      .join(', ')
                  }}
                </span>
              </div>
              <div class="flex justify-between">
                <span class="text-gray-600 dark:text-gray-400">Requesting:</span>
                <span class="text-gray-900 dark:text-white">
                  {{
                    form.assetsRequested
                      .map(
                        a =>
                          `${formatAssetAmount(a.amount, a.type)} ${a.symbol || a.type.toUpperCase()}`
                      )
                      .join(', ')
                  }}
                </span>
              </div>
              <div class="flex justify-between border-t border-gray-200 dark:border-gray-600 pt-2">
                <span class="font-medium text-gray-700 dark:text-gray-300">Fee:</span>
                <span class="font-medium text-gray-900 dark:text-white">{{ form.fee }} XCH</span>
              </div>
            </div>
          </div>

          <!-- Error/Success Messages -->
          <div
            v-if="errorMessage"
            class="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"
          >
            <div class="flex items-center">
              <i class="pi pi-exclamation-triangle text-red-600 dark:text-red-400 mr-2"></i>
              <p class="text-red-800 dark:text-red-200">{{ errorMessage }}</p>
            </div>
          </div>

          <div
            v-if="successMessage"
            class="p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg"
          >
            <div class="flex items-center">
              <i class="pi pi-check-circle text-green-600 dark:text-green-400 mr-2"></i>
              <p class="text-green-800 dark:text-green-200">{{ successMessage }}</p>
            </div>
          </div>

          <!-- Actions -->
          <div class="flex justify-end space-x-3">
            <button
              type="button"
              @click="$emit('close')"
              class="px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-lg transition-colors duration-200"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="!isFormValid || isSubmitting"
              class="px-6 py-2 bg-primary-600 hover:bg-primary-700 disabled:bg-gray-400 dark:disabled:bg-gray-600 text-white font-medium rounded-lg transition-colors duration-200 flex items-center"
            >
              <i v-if="isSubmitting" class="pi pi-spin pi-spinner mr-2"></i>
              <i v-else class="pi pi-plus mr-2"></i>
              {{ isSubmitting ? 'Creating...' : 'Create Offer' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { useWalletDataService } from '@/features/walletConnect/services/WalletDataService'
  import { useOfferStorage } from '@/shared/composables/useOfferStorage'
  import { useTickerData } from '@/shared/composables/useTickerData'
  import { formatAssetAmount, xchToMojos } from '@/shared/utils/chia-units'
  import type { CreateOfferForm, OfferDetails } from '@/types/offer.types'
  import { computed, reactive, ref } from 'vue'

  interface Emits {
    (e: 'close'): void
    (e: 'offer-created', offer: OfferDetails): void
  }

  const emit = defineEmits<Emits>()

  // Services
  const walletDataService = useWalletDataService()
  const offerStorage = useOfferStorage()
  const { availableCatTokens, getCatTokenInfo } = useTickerData()

  // Form state
  const form = reactive<CreateOfferForm>({
    assetsOffered: [],
    assetsRequested: [],
    fee: 0,
    memo: '',
    expirationHours: 24,
  })

  // UI state
  const isSubmitting = ref(false)
  const errorMessage = ref('')
  const successMessage = ref('')

  // Computed
  const isFormValid = computed(() => {
    return (
      form.assetsOffered.length > 0 &&
      form.assetsRequested.length > 0 &&
      form.assetsOffered.every(
        asset => asset.amount > 0 && (asset.type === 'xch' || asset.assetId)
      ) &&
      form.assetsRequested.every(
        asset => asset.amount > 0 && (asset.type === 'xch' || asset.assetId)
      ) &&
      form.fee >= 0
    )
  })

  // Methods
  const addOfferedAsset = () => {
    form.assetsOffered.push({
      assetId: '',
      amount: 0,
      type: 'xch',
      symbol: '',
      searchQuery: '',
      showDropdown: false,
    })
  }

  const removeOfferedAsset = (index: number) => {
    form.assetsOffered.splice(index, 1)
  }

  const addRequestedAsset = () => {
    form.assetsRequested.push({
      assetId: '',
      amount: 0,
      type: 'xch',
      symbol: '',
      searchQuery: '',
      showDropdown: false,
    })
  }

  const removeRequestedAsset = (index: number) => {
    form.assetsRequested.splice(index, 1)
  }

  // Search functionality
  const filteredCatTokens = (searchQuery: string) => {
    if (!searchQuery) return availableCatTokens.value
    const query = searchQuery.toLowerCase()
    return availableCatTokens.value.filter(
      token =>
        token.ticker.toLowerCase().includes(query) || token.name.toLowerCase().includes(query)
    )
  }

  const selectCatToken = (
    asset: { assetId: string; symbol: string; searchQuery: string; showDropdown: boolean },
    token: { assetId: string; ticker: string }
  ) => {
    asset.assetId = token.assetId
    asset.symbol = token.ticker
    asset.searchQuery = token.ticker
    asset.showDropdown = false
  }

  const clearAssetSelection = (asset: {
    assetId: string
    symbol: string
    searchQuery: string
    showDropdown: boolean
  }) => {
    asset.assetId = ''
    asset.symbol = ''
    asset.searchQuery = ''
    asset.showDropdown = false
  }

  const handleSubmit = async () => {
    errorMessage.value = ''
    successMessage.value = ''

    if (!isFormValid.value) {
      errorMessage.value = 'Please fill in all required fields'
      return
    }

    isSubmitting.value = true

    try {
      // Helper function to convert amounts to the smallest unit based on asset type
      // Different assets have different decimal places:
      // - XCH: 12 decimal places (1 XCH = 1,000,000,000,000 mojos)
      // - CAT: May need conversion to smallest unit (1 CAT = 1000 smallest units?)
      // - NFT: Whole numbers only
      const convertToSmallestUnit = (amount: number, assetType: string): number => {
        switch (assetType) {
          case 'xch':
            return xchToMojos(amount) // XCH to mojos using shared utility
          case 'cat':
            // CAT tokens might need conversion to smallest unit
            // If 1 CAT shows as 0.001 in wallet, then multiply by 1000
            return Math.round(amount * 1000)
          case 'nft':
            return Math.floor(amount) // NFTs are whole numbers
          default:
            return amount // Default to exact amount for unknown tokens
        }
      }

      // Convert form assets to the format expected by the wallet
      const offerAssets = form.assetsOffered.map(asset => ({
        assetId: asset.type === 'xch' ? '' : asset.assetId,
        amount: convertToSmallestUnit(asset.amount, asset.type),
      }))

      const requestAssets = form.assetsRequested.map(asset => ({
        assetId: asset.type === 'xch' ? '' : asset.assetId,
        amount: convertToSmallestUnit(asset.amount, asset.type),
      }))

      // Debug logging for CAT token amounts
      // console.log('Form assets offered:', form.assetsOffered)
      // console.log('Form assets requested:', form.assetsRequested)
      // console.log('Converted offer assets:', offerAssets)
      // console.log('Converted request assets:', requestAssets)

      const result = await walletDataService.createOffer({
        walletId: 1,
        offerAssets,
        requestAssets,
        fee: convertToSmallestUnit(form.fee, 'xch'), // Fee is always in XCH
      })

      // Debug logging
      // console.log('Offer creation result:', result)
      // console.log('Result tradeId:', result?.tradeId)
      // console.log('Result id:', result?.id)
      // console.log('Result offer:', result?.offer)

      if (!result || !result.offer) {
        throw new Error('Wallet did not return a valid offer string')
      }

      const newOffer: OfferDetails = {
        id: result?.id || Date.now().toString(),
        tradeId: result?.tradeId || result?.id || 'unknown',
        offerString: result?.offer || '',
        status: 'active',
        createdAt: new Date(),
        assetsOffered: form.assetsOffered.map(asset => ({
          assetId: asset.assetId || '',
          amount: asset.amount,
          type: asset.type,
          symbol: asset.symbol || asset.type.toUpperCase(),
        })),
        assetsRequested: form.assetsRequested.map(asset => ({
          assetId: asset.assetId || '',
          amount: asset.amount,
          type: asset.type,
          symbol: asset.symbol || asset.type.toUpperCase(),
        })),
        fee: form.fee,
        creatorAddress: walletDataService.address.data.value?.address || 'unknown',
      }

      // Save offer to IndexedDB
      await offerStorage.saveOffer(newOffer, true) // true = isLocal

      successMessage.value = 'Offer created successfully!'
      emit('offer-created', newOffer)

      // Reset form
      form.assetsOffered = []
      form.assetsRequested = []
      form.fee = 0
      form.memo = ''
      form.expirationHours = 24
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error occurred'
      errorMessage.value = `Failed to create offer: ${errorMsg}`
    } finally {
      isSubmitting.value = false
    }
  }

  // Initialize with one asset in each section
  addOfferedAsset()
  addRequestedAsset()
</script>

<style scoped>
  /* Custom scrollbar for modal */
  .overflow-y-auto::-webkit-scrollbar {
    width: 6px;
  }

  .overflow-y-auto::-webkit-scrollbar-track {
    @apply bg-gray-100 dark:bg-gray-600 rounded;
  }

  .overflow-y-auto::-webkit-scrollbar-thumb {
    @apply bg-gray-300 dark:bg-gray-500 rounded;
  }

  .overflow-y-auto::-webkit-scrollbar-thumb:hover {
    @apply bg-gray-400 dark:bg-gray-400;
  }
</style>
